### ISSUE TITLE
如何增加cc和bcc，如果收件人为2个或者以上，怎么添加多个收件人

### ISSUE THREAD

**Issue by daifai** [devcxl/cloudflare-email-sender#2]
如何增加cc和bcc，如果收件人为2个或者以上，怎么添加多个收件人

**Comment by devcxl** [comment]
你可以参考 mailchannels 的发送接口[文档](https://api.mailchannels.net/tx/v1/documentation) 更改`src/email.ts`中的代码

**Comment by daifai** [comment]
> 你可以参考 mailchannels 的发送接口[文档](https://api.mailchannels.net/tx/v1/documentation) 更改`src/email.ts`中的代码

收到，正在修改，谢谢
