### ISSUE TITLE
发送显示失败 {"success":false}

### ISSUE THREAD

**Issue by spiritLHLS** [devcxl/cloudflare-email-sender#3]
请求增加更多提示信息，不知道是什么配置出了问题

**Comment by devcxl** [comment]
自 2024 年 8 月 31 日起，MailChannels 不再为 Cloudflare Workers 用户提供免费电子邮件发送服务

- https://support.mailchannels.com/hc/en-us/articles/26814255454093-End-of-Life-Notice-Cloudflare-Workers

**Comment by spiritLHLS** [comment]
看样子没法免费的发信了，只通过免费的资源的话

**Comment by devcxl** [comment]
@spiritLHLS 目前切换到了 Resend 可以免费发信 但是有限制
